"
  CREATE TABLE "DIP"."MASTER_DEPARTMENT" 
   (	"DEPT_ID" NUMBER, 
	"DEPT_CODE" CHAR(10) NOT NULL ENABLE, 
	"DEPT_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"STATUS" CHAR(1), 
	"CREATED_DT" DATE DEFAULT SYSDATE, 
	 CHECK (STATUS IN ('A','I')) ENABLE, 
	 PRIMARY KEY ("DEPT_ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("DEPT_CODE")
  USING INDEX  ENABLE
   ) "
   
   "
  CREATE TABLE "DIP"."EMP_CONTACT" 
   (	"CONTACT_ID" NUMBER, 
	"EMP_CODE" CHAR(10), 
	"EMAIL" VARCHAR2(50), 
	"ALT_NAME" NCHAR(10), 
	"ADDRESS" NVARCHAR2(50), 
	 PRIMARY KEY ("CONTACT_ID")
  USING INDEX  ENABLE
   ) "
   
   "
  CREATE TABLE "DIP"."EMP_TIMESTAMPS" 
   (	"EMP_ID" NUMBER, 
	"CREATED_TS" TIMESTAMP (6), 
	"UPDATED_TS" TIMESTAMP (6) WITH TIME ZONE, 
	"LOCAL_TS" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	 PRIMARY KEY ("EMP_ID")
  USING INDEX  ENABLE
   ) "
   
   "
  CREATE TABLE "DIP"."EMP_INTERVALS" 
   (	"EMP_ID" NUMBER, 
	"EXPERIENCE_YM" INTERVAL YEAR (2) TO MONTH, 
	"WORK_DURATION_DS" INTERVAL DAY (2) TO SECOND (6), 
	 PRIMARY KEY ("EMP_ID")
  USING INDEX  ENABLE
   ) "
   
   "
  CREATE TABLE "DIP"."FINANCIAL_METRICS" 
   (	"METRIC_ID" NUMBER, 
	"FLOAT_VALUE" BINARY_FLOAT, 
	"DOUBLE_VALUE" BINARY_DOUBLE, 
	 PRIMARY KEY ("METRIC_ID")
  USING INDEX  ENABLE
   ) "
   
   "
  CREATE TABLE "DIP"."DOC_LONG_DATA" 
   (	"DOC_ID" NUMBER, 
	"DOC_TEXT" LONG, 
	 PRIMARY KEY ("DOC_ID")
  USING INDEX  ENABLE
   ) "
   
   "
  CREATE TABLE "DIP"."DOC_LOB_STORE" 
   (	"DOC_ID" NUMBER, 
	"TEXT_DATA" CLOB, 
	"UNICODE_TEXT" NCLOB, 
	"BINARY_DATA" BLOB, 
	"DOC_BINARY" LONG RAW, 
	 PRIMARY KEY ("DOC_ID")
  USING INDEX  ENABLE
   ) "
   
   "
  CREATE TABLE "DIP"."FILE_REFERENCE" 
   (	"FILE_ID" NUMBER, 
	"FILE_LOC" BFILE, 
	 PRIMARY KEY ("FILE_ID")
  USING INDEX  ENABLE
   ) "
   
   "
  CREATE TABLE "DIP"."RAW_UUID_STORE" 
   (	"RECORD_ID" NUMBER(*,0), 
	"UUID_RAW" RAW(16), 
	 PRIMARY KEY ("RECORD_ID")
  USING INDEX  ENABLE
   ) "
   
   "
  CREATE TABLE "DIP"."ROWID_TRACKING" 
   (	"TRACK_ID" NUMBER, 
	"ROW_LOC" ROWID, 
	"UROW_LOC" UROWID (4000), 
	 PRIMARY KEY ("TRACK_ID")
  USING INDEX  ENABLE
   ) "
   
   "
  CREATE TABLE "DIP"."XML_JSON_STORE" 
   (	"DOC_ID" NUMBER, 
	"XML_DATA" "XMLTYPE", 
	"JSON_DATA" JSON, 
	 CHECK (JSON_DATA IS JSON) ENABLE, 
	 PRIMARY KEY ("DOC_ID")
  USING INDEX  ENABLE
   ) "
   
   "
  CREATE TABLE "DIP"."GEOSPATIAL_DATA" 
   (	"GEO_ID" NUMBER, 
	"LOCATION" "SDO_GEOMETRY", 
	 PRIMARY KEY ("GEO_ID")
  USING INDEX  ENABLE
   ) 
 VARRAY "LOCATION"."SDO_ELEM_INFO" STORE AS SECUREFILE LOB 
 VARRAY "LOCATION"."SDO_ORDINATES" STORE AS SECUREFILE LOB "
 
 "
  CREATE TABLE "DIP"."AUDIT_DEFAULTS" 
   (	"AUDIT_ID" NUMBER, 
	"ACTION_TYPE" VARCHAR2(20) NOT NULL ENABLE, 
	"ACTION_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" CHAR(1) DEFAULT 'Y', 
	 CHECK (STATUS IN ('Y','N')) ENABLE, 
	 PRIMARY KEY ("AUDIT_ID")
  USING INDEX  ENABLE
   ) 
   